[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dl-myo"
version = "0.0.3"
authors = [
  { name="Iori Mizutani", email="iori.mizutani@gmail.com" },
]
Maintainers = [
  { name="Iori Mizutani", email="iori.mizutani@gmail.com" },
]
description = "A middleware to manage Myo EMG streams"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Framework :: AsyncIO",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
]

[project.urls]
"Homepage" = "https://github.com/iomz/dl-myo"
"Bug Tracker" = "https://github.com/iomz/dl-myo/issues"

[tool]
[tool.pyright]
#reportGeneralTypeIssues = false
