name: pypi
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  release:
    env:
      python-version: "3.11"
      poetry-version: "1.5.1"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/dl-myo
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.poetry-version }}
      - name: Build
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --no-interaction
          poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
